- name: install nginx and start
  hosts: web
  become: yes
  tasks:
  - name: inastall nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start service
    ansible.builtin.service:
      name: nginx
      state: started    